name: 'Install and Run Checkov'
description: 'Install Checkov security scanner and run scans with Terragrunt support'

inputs:
  # Installation inputs
  version:
    description: 'Checkov version to install'
    required: false
    default: '3.2.499'
  
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'

  # Scan configuration inputs
  run-scan:
    description: 'Whether to run security scan after installation'
    required: false
    default: 'true'

  workingDirectory:
    description: 'Working directory for Checkov scan'
    required: false
    default: '.'

  checkovSkipChecks:
    description: 'Comma-separated list of checks to skip'
    required: false
    default: ''

  scan-terragrunt-cache:
    description: 'Scan Terragrunt cache directory if found'
    required: false
    default: 'true'

  output-format:
    description: 'Output format (cli, json, junitxml, sarif, github_failed_only)'
    required: false
    default: 'cli,junitxml'

  framework:
    description: 'IaC framework to scan (terraform, kubernetes, dockerfile, all)'
    required: false
    default: 'terraform'

  soft-fail:
    description: 'Do not fail the build if security issues are found'
    required: false
    default: 'true'

outputs:
  checkov-version:
    description: 'Installed Checkov version'
    value: ${{ steps.install.outputs.version }}
  
  scan-completed:
    description: 'Whether scan was completed'
    value: ${{ steps.scan.outputs.completed }}

  scan-directory:
    description: 'Directory that was scanned'
    value: ${{ steps.scan.outputs.scanned-dir }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Checkov
      id: install
      shell: bash
      run: |
        echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"
        echo " ðŸ”’ Installing Checkov"
        echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"
        
        if [ "${{ inputs.version }}" = "latest" ]; then
          pip install --upgrade pip
          pip install checkov
        else
          pip install --upgrade pip
          pip install checkov==${{ inputs.version }}
        fi
        
        VERSION=$(checkov --version | head -n 1)
        echo " Checkov installed successfully"
        echo "$VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"

    - name: Run Checkov Security Scan
      id: scan
      if: inputs.run-scan == 'true'
      shell: bash
      working-directory: ${{ inputs.workingDirectory }}
      continue-on-error: true
      run: |
        echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"
        echo "  Running Checkov Security Scan"
        echo " Working Directory: $(pwd)"
        echo " Framework: ${{ inputs.framework }}"
        echo " Output Format: ${{ inputs.output-format }}"
        echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"
        
        # Prepare skip checks argument
        SKIP_CHECKS="${{ inputs.checkovSkipChecks }}"
        SKIP_ARG=""
        if [ -n "${SKIP_CHECKS}" ]; then
          echo "  Skipping checks: ${SKIP_CHECKS}"
          SKIP_ARG="--skip-check ${SKIP_CHECKS}"
        fi
        
        # Prepare output format arguments
        OUTPUT_FORMATS="${{ inputs.output-format }}"
        OUTPUT_ARGS=""
        for format in ${OUTPUT_FORMATS//,/ }; do
          OUTPUT_ARGS="${OUTPUT_ARGS} --output ${format}"
        done
        
        # Prepare soft-fail argument
        SOFT_FAIL_ARG=""
        if [ "${{ inputs.soft-fail }}" = "true" ]; then
          SOFT_FAIL_ARG="--soft-fail"
        fi
        
        # Determine scan directory
        SCAN_DIR="."
        SCAN_TYPE="working directory"
        
        # Check if we should scan Terragrunt cache
        if [ "${{ inputs.scan-terragrunt-cache }}" = "true" ]; then
          echo "ðŸ”Ž Looking for Terragrunt cache directory..."
          
          # Find Terraform files in cache
          CACHE_DIR=$(find . -type d -name ".terragrunt-cache" -print -quit 2>/dev/null)
          
          if [ -n "${CACHE_DIR}" ]; then
            # Find the actual Terraform module directory within cache
            TF_MODULE=$(find "${CACHE_DIR}" -type f -name "*.tf" -exec dirname {} \; | head -n 1)
            
            if [ -n "${TF_MODULE}" ]; then
              SCAN_DIR="${TF_MODULE}"
              SCAN_TYPE="Terragrunt cache"
              echo " Found Terragrunt cache: ${SCAN_DIR}"
            else
              echo "  Terragrunt cache found but no .tf files, scanning working directory"
            fi
          else
            echo "  No Terragrunt cache found, scanning working directory"
          fi
        fi
        
        echo ""
        echo " Scanning ${SCAN_TYPE}: ${SCAN_DIR}"
        echo ""
        
        # Build and run Checkov command
        CHECKOV_CMD="checkov -d \"${SCAN_DIR}\" \
          --framework ${{ inputs.framework }} \
          ${OUTPUT_ARGS} \
          --output-file-path . \
          ${SOFT_FAIL_ARG} \
          ${SKIP_ARG}"
        
        echo "ðŸš€ Executing: ${CHECKOV_CMD}"
        echo ""
        echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"
        echo ""
        
        # Run Checkov
        eval ${CHECKOV_CMD} || true
        
        # Set outputs
        echo "completed=true" >> $GITHUB_OUTPUT
        echo "scanned-dir=${SCAN_DIR}" >> $GITHUB_OUTPUT
        
        echo ""
        echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"
        echo "  Checkov scan completed"
        echo "  Results saved to current directory"
        echo "â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”"

    - name: Upload Checkov Results
      if: inputs.run-scan == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: checkov-security-report
        path: |
          ${{ inputs.workingDirectory }}/results_cli.txt
          ${{ inputs.workingDirectory }}/results_junitxml.xml
          ${{ inputs.workingDirectory }}/results_json.json
          ${{ inputs.workingDirectory }}/results_sarif.sarif
        if-no-files-found: ignore
        retention-days: 30

    - name: Generate Summary
      if: inputs.run-scan == 'true'
      shell: bash
      working-directory: ${{ inputs.workingDirectory }}
      run: |
        echo "##  Checkov Security Scan Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Checkov Version:** ${{ steps.install.outputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo "**Scanned Directory:** \`${{ steps.scan.outputs.scanned-dir }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Framework:** \`${{ inputs.framework }}\`" >> $GITHUB_STEP_SUMMARY
        echo "**Output Formats:** \`${{ inputs.output-format }}\`" >> $GITHUB_STEP_SUMMARY
        
        if [ -n "${{ inputs.checkovSkipChecks }}" ]; then
          echo "**Skipped Checks:** \`${{ inputs.checkovSkipChecks }}\`" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "ðŸ“Š Security scan results have been uploaded as artifacts." >> $GITHUB_STEP_SUMMARY